// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using veilingklok;

#nullable disable

namespace veilingklok.Migrations
{
    [DbContext(typeof(VeilingContext))]
    partial class VeilingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("veilingklok.Aanvoerder", b =>
                {
                    b.Property<int>("AanvoerderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("aanvoerder_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AanvoerderId"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("adres");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("int")
                        .HasColumnName("gebruiker_id");

                    b.Property<string>("IbanHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("iban_hash");

                    b.Property<string>("KvkNummer")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("kvk_nummer");

                    b.HasKey("AanvoerderId");

                    b.HasIndex("GebruikerId");

                    b.ToTable("Aanvoerders");
                });

            modelBuilder.Entity("veilingklok.Bod", b =>
                {
                    b.Property<int>("BodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bod_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BodId"));

                    b.Property<decimal>("Bedrag")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("bedrag");

                    b.Property<int>("KoperId")
                        .HasColumnType("int")
                        .HasColumnName("koper_id");

                    b.Property<DateTime>("Tijdstip")
                        .HasColumnType("datetime2")
                        .HasColumnName("tijdstip");

                    b.Property<int>("VeilingId")
                        .HasColumnType("int")
                        .HasColumnName("veiling_id");

                    b.HasKey("BodId");

                    b.HasIndex("KoperId");

                    b.HasIndex("VeilingId");

                    b.ToTable("Biedingen");
                });

            modelBuilder.Entity("veilingklok.Gebruiker", b =>
                {
                    b.Property<int>("GebruikerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("gebruiker_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GebruikerId"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("naam");

                    b.Property<string>("WachtwoordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("wachtwoord_hash");

                    b.HasKey("GebruikerId");

                    b.ToTable("Gebruikers");
                });

            modelBuilder.Entity("veilingklok.Koper", b =>
                {
                    b.Property<int>("KoperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("koper_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KoperId"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("adres");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("int")
                        .HasColumnName("gebruiker_id");

                    b.Property<string>("IbanHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("iban_hash");

                    b.Property<string>("KvkNummer")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("kvk_nummer");

                    b.HasKey("KoperId");

                    b.HasIndex("GebruikerId");

                    b.ToTable("Kopers");
                });

            modelBuilder.Entity("veilingklok.Product", b =>
                {
                    b.Property<int>("ArtikelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("artikel_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtikelId"));

                    b.Property<int>("AanvoerderId")
                        .HasColumnType("int")
                        .HasColumnName("aanvoerder_id");

                    b.Property<string>("Afbeelding")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("afbeelding");

                    b.Property<int?>("Hoeveelheid")
                        .HasColumnType("int")
                        .HasColumnName("hoeveelheid");

                    b.Property<string>("KlokLocatie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("kloklocatie");

                    b.Property<decimal?>("MinimumPrijs")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("minimumprijs");

                    b.Property<int?>("Potmaat")
                        .HasColumnType("int")
                        .HasColumnName("potmaat");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("soort");

                    b.Property<decimal?>("Steellengte")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("steellengte");

                    b.HasKey("ArtikelId");

                    b.HasIndex("AanvoerderId");

                    b.ToTable("Producten");
                });

            modelBuilder.Entity("veilingklok.Veiling", b =>
                {
                    b.Property<int>("VeilingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("veiling_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeilingId"));

                    b.Property<int?>("ArtikelId")
                        .HasColumnType("int")
                        .HasColumnName("artikel_id");

                    b.Property<DateTime>("EindTijd")
                        .HasColumnType("datetime2")
                        .HasColumnName("eindtijd");

                    b.Property<DateTime>("StartTijd")
                        .HasColumnType("datetime2")
                        .HasColumnName("starttijd");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("VeilingmeesterId")
                        .HasColumnType("int")
                        .HasColumnName("veilingmeester_id");

                    b.HasKey("VeilingId");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("VeilingmeesterId");

                    b.ToTable("Veilingen", t =>
                        {
                            t.HasCheckConstraint("CK_Veiling_Status", "status IN ('Idle', 'Ongoing', 'Done')");
                        });
                });

            modelBuilder.Entity("veilingklok.Veilingmeester", b =>
                {
                    b.Property<int>("VeilingmeesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("veilingmeester_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeilingmeesterId"));

                    b.Property<int>("GebruikerId")
                        .HasColumnType("int")
                        .HasColumnName("gebruiker_id");

                    b.HasKey("VeilingmeesterId");

                    b.HasIndex("GebruikerId");

                    b.ToTable("Veilingmeesters");
                });

            modelBuilder.Entity("veilingklok.Aanvoerder", b =>
                {
                    b.HasOne("veilingklok.Gebruiker", "Gebruiker")
                        .WithMany("Aanvoerders")
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("veilingklok.Bod", b =>
                {
                    b.HasOne("veilingklok.Koper", "Koper")
                        .WithMany("Biedingen")
                        .HasForeignKey("KoperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("veilingklok.Veiling", "Veiling")
                        .WithMany("Biedingen")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Koper");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("veilingklok.Koper", b =>
                {
                    b.HasOne("veilingklok.Gebruiker", "Gebruiker")
                        .WithMany("Kopers")
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("veilingklok.Product", b =>
                {
                    b.HasOne("veilingklok.Aanvoerder", "Aanvoerder")
                        .WithMany("Producten")
                        .HasForeignKey("AanvoerderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aanvoerder");
                });

            modelBuilder.Entity("veilingklok.Veiling", b =>
                {
                    b.HasOne("veilingklok.Product", "Product")
                        .WithMany("Veilingen")
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("veilingklok.Veilingmeester", "Veilingmeester")
                        .WithMany("Veilingen")
                        .HasForeignKey("VeilingmeesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Veilingmeester");
                });

            modelBuilder.Entity("veilingklok.Veilingmeester", b =>
                {
                    b.HasOne("veilingklok.Gebruiker", "Gebruiker")
                        .WithMany("Veilingmeesters")
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("veilingklok.Aanvoerder", b =>
                {
                    b.Navigation("Producten");
                });

            modelBuilder.Entity("veilingklok.Gebruiker", b =>
                {
                    b.Navigation("Aanvoerders");

                    b.Navigation("Kopers");

                    b.Navigation("Veilingmeesters");
                });

            modelBuilder.Entity("veilingklok.Koper", b =>
                {
                    b.Navigation("Biedingen");
                });

            modelBuilder.Entity("veilingklok.Product", b =>
                {
                    b.Navigation("Veilingen");
                });

            modelBuilder.Entity("veilingklok.Veiling", b =>
                {
                    b.Navigation("Biedingen");
                });

            modelBuilder.Entity("veilingklok.Veilingmeester", b =>
                {
                    b.Navigation("Veilingen");
                });
#pragma warning restore 612, 618
        }
    }
}
