// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using veilingklok;

#nullable disable

namespace veilingklok.Migrations
{
    [DbContext(typeof(VeilingContext))]
    partial class VeilingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("veilingklok.Models.Gebruiker", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("naam");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Gebruiker", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("veilingklok.Models.Product", b =>
                {
                    b.Property<int>("ArtikelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("artikel_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtikelId"));

                    b.Property<string>("Afbeelding")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("afbeelding");

                    b.Property<string>("Gebruiker_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("gebruiker_id");

                    b.Property<int?>("Hoeveelheid")
                        .HasColumnType("int")
                        .HasColumnName("hoeveelheid");

                    b.Property<string>("KlokLocatie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("kloklocatie");

                    b.Property<decimal?>("MinimumPrijs")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("minimumprijs");

                    b.Property<int?>("Potmaat")
                        .HasColumnType("int")
                        .HasColumnName("potmaat");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("soort");

                    b.Property<decimal?>("Steellengte")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("steellengte");

                    b.Property<int?>("VeilingId")
                        .HasColumnType("int");

                    b.HasKey("ArtikelId");

                    b.HasIndex("Gebruiker_id");

                    b.HasIndex("VeilingId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("veilingklok.Models.Veiling", b =>
                {
                    b.Property<int>("VeilingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("veiling_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeilingId"));

                    b.Property<int?>("ArtikelId")
                        .HasColumnType("int")
                        .HasColumnName("artikel_id");

                    b.Property<DateTime>("EindTijd")
                        .HasColumnType("datetime2")
                        .HasColumnName("eindtijd");

                    b.Property<string>("Gebruiker_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("gebruiker_id");

                    b.Property<string>("KlantId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("klant_id");

                    b.Property<decimal?>("Koopprijs")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("koopprijs");

                    b.Property<decimal?>("MinimumPrijs")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("minimumprijs");

                    b.Property<DateTime>("StartTijd")
                        .HasColumnType("datetime2")
                        .HasColumnName("starttijd");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("VeilingNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("veilingnaam");

                    b.HasKey("VeilingId");

                    b.HasIndex("Gebruiker_id");

                    b.HasIndex("KlantId");

                    b.ToTable("Veiling", null, t =>
                        {
                            t.HasCheckConstraint("CK_Veiling_Status", "status IN ('Idle', 'Ongoing', 'Done')");
                        });
                });

            modelBuilder.Entity("veilingklok.Models.Aanvoerder", b =>
                {
                    b.HasBaseType("veilingklok.Models.Gebruiker");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("adres");

                    b.Property<string>("IbanHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("iban_hash");

                    b.Property<string>("KvkNummer")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("kvk_nummer");

                    b.ToTable("Aanvoerder", (string)null);
                });

            modelBuilder.Entity("veilingklok.Models.Koper", b =>
                {
                    b.HasBaseType("veilingklok.Models.Gebruiker");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("adres");

                    b.Property<string>("IbanHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("iban_hash");

                    b.Property<string>("KvkNummer")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("kvk_nummer");

                    b.ToTable("Koper", (string)null);
                });

            modelBuilder.Entity("veilingklok.Models.Veilingmeester", b =>
                {
                    b.HasBaseType("veilingklok.Models.Gebruiker");

                    b.ToTable("Veilingmeester", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("veilingklok.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("veilingklok.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("veilingklok.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("veilingklok.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("veilingklok.Models.Product", b =>
                {
                    b.HasOne("veilingklok.Models.Aanvoerder", "Aanvoerder")
                        .WithMany("Producten")
                        .HasForeignKey("Gebruiker_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("veilingklok.Models.Veiling", null)
                        .WithMany("Producten")
                        .HasForeignKey("VeilingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Aanvoerder");
                });

            modelBuilder.Entity("veilingklok.Models.Veiling", b =>
                {
                    b.HasOne("veilingklok.Models.Veilingmeester", "Veilingmeester")
                        .WithMany("Veilingen")
                        .HasForeignKey("Gebruiker_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("veilingklok.Models.Koper", "Koper")
                        .WithMany()
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Koper");

                    b.Navigation("Veilingmeester");
                });

            modelBuilder.Entity("veilingklok.Models.Aanvoerder", b =>
                {
                    b.HasOne("veilingklok.Models.Gebruiker", null)
                        .WithOne()
                        .HasForeignKey("veilingklok.Models.Aanvoerder", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("veilingklok.Models.Koper", b =>
                {
                    b.HasOne("veilingklok.Models.Gebruiker", null)
                        .WithOne()
                        .HasForeignKey("veilingklok.Models.Koper", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("veilingklok.Models.Veilingmeester", b =>
                {
                    b.HasOne("veilingklok.Models.Gebruiker", null)
                        .WithOne()
                        .HasForeignKey("veilingklok.Models.Veilingmeester", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("veilingklok.Models.Veiling", b =>
                {
                    b.Navigation("Producten");
                });

            modelBuilder.Entity("veilingklok.Models.Aanvoerder", b =>
                {
                    b.Navigation("Producten");
                });

            modelBuilder.Entity("veilingklok.Models.Veilingmeester", b =>
                {
                    b.Navigation("Veilingen");
                });
#pragma warning restore 612, 618
        }
    }
}
